"""Add profile_image column to User

Revision ID: 27f819c6a310
Revises: bd33e9ce1822
Create Date: 2025-10-16 19:44:44.333856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f819c6a310'
down_revision = 'bd33e9ce1822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thought_likes')
    with op.batch_alter_table('thought', schema=None) as batch_op:
        batch_op.alter_column('mood',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=200), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('profile_image')

    with op.batch_alter_table('thought', schema=None) as batch_op:
        batch_op.alter_column('mood',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    op.create_table('thought_likes',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('thought_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['thought_id'], ['thought.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'thought_id')
    )
    # ### end Alembic commands ###
