"""Add mood column to Thought

Revision ID: bd33e9ce1822
Revises: 
Create Date: 2025-10-11 22:02:27.937097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd33e9ce1822'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thought', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thought', schema=None) as batch_op:
        batch_op.drop_column('mood')

    # ### end Alembic commands ###
